spring:
  application:
    name: openapi-service-base-gateway

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10